### ISSUE TITLE
Usage of scalar types in hipsycl without cl_uint

### ISSUE THREAD

**Issue by aendk** [AdaptiveCpp/AdaptiveCpp#479] opened 2021-02-28 16:27 UTC
According to the [feature-list](https://github.com/hipSYCL/featuresupport), hipsycl has removed support for types such as ```cl_int```.

I want to compare values against an unsigned integer in my kernel function, what is the best way to do so?
Declaring this scalar as ```cl::sycl::cl_uint``` does not work(as expected), and comparisons of a value in the buffered vector (```hipsycl::sycl::vec<unsigned int, 4>```) with the standard c++ ```uint``` fail as well.

Any thoughts?
Thanks

**Comment by illuhad** [comment] 2021-02-28 17:01
Can you please describe in more detail what you want to do, ideally with a code reproducer and the error message?

You don't need `cl_uint` for such comparisons, e.g. 
```
sycl::vec<unsigned int, 4> v = ...;
unsigned int val = 2;
val == v.x();
```
should work.

**Comment by aendk** [comment] 2021-03-01 07:39
The kernel acts as a filter for a database-query. So if x,y,z apply add a to a sum
x in this case is the year ```1994```.

This is the first error message:
```
sycl_main.cpp: In lambda function:
sycl_main.cpp:204:30: error: could not convert ‘hipsycl::sycl::operator==(year.hipsycl::sycl::accessor<hipsycl::sycl::vec<unsigned int, 4>, 1, hipsycl::sycl::access::mode::read, hipsycl::sycl::access::target::global_buffer, hipsycl::sycl::access::placeholder::false_t>::operator[]<>(0), ninetyfour)’ from ‘hipsycl::sycl::vec<int, 4>’ to ‘bool’
  204 |                 if ((year[0] == ninetyfour)
      |                     ~~~~~~~~~^~~~~~~~~~~~~~
      |                              |
      |                              hipsycl::sycl::vec<int, 4>

```

Here i have initialized ```ninetyfour``` as you have recommended in your post above, it does not work.

**Comment by aendk** [comment] 2021-03-01 07:45
@dpanugroho this will be useful for laert, once he tries to compile on hipsycl, 
as other sycl-implementations might show other behavior.

**Comment by illuhad** [comment] 2021-03-01 11:24
Okay, I think I know what is going on and I believe hipSYCL behaves correctly.

From your error message I can see that `year` is a 1D accessor of `vec<unsigned int, 4>`. So, year[0] refers to one `vec` object. As a consequence, your `operator==` compares `vec` with `unsigned int`.

This causes a `vec` to be constructed for the right hand side which contains four times the value `ninetyfour`, as per the SYCL specification. Now you have a comparison between two `vec` objects, and the SYCL specification says that this should return a `vec` that contains the result of the comparison for each component.

This is why you don't end up with a `bool`, but with a `vec`, and it's the correct behavior IMO.

**Comment by aendk** [comment] 2021-03-01 21:23
@illuhad  thank you for your insight. This behavior is totally new for me(as is gpu processing/sylc/cuda etc). 

I can probably work around this. 
However, is there a simpler way to just cast the element on the left hand side to an ```unsigned int``` (I tried basic copying unsuccessfully ) and then do the comparison that way, or is that train of thought also not really supported on gpu?

[Your initial reply ](https://github.com/illuhad/hipSYCL/issues/479#issuecomment-787483800) is not applicable, because I have to check for each position of the vector  and ```v.x()``` only checks the first.

**Comment by illuhad** [comment] 2021-03-01 21:44
This has nothing to do with GPU programming models, it's just regular C++ rules and would be exactly the same if you had your code outside of the kernel, in host code.

I'm not sure I really understand well enough what you want to accomplish to answer your question. `vec` is something like `std::array` except that it is built to potentially leverage SIMD vectorization.
What do you hope to gain by putting years into a 4-component array-like type? Do you want to store years by their decimal digits? Then you cannot expect a conversion to or comparison with an unsigned int to work unless you manually teach C++ how to combine individual decimal digits back into a single number (e.g. `v[0]*1000 + v[1]*100 + v[2]*10 + v[3]`).

>  I tried basic copying unsuccessfully

Sure, if you copy a `vec` consisting of four unsigned ints into a single unsigned int, how can C++ know how to combine the 4 numbers into one? Again, nothing GPU-specific, just C++ :-) You need to tell it what you want to happen.

I'm not sure why you want to store years (year numbers?) in a vec in the first place. It seems quite wasteful and inefficient to store a single 32-bit number like a year using multiple 32-bit numbers..

**Comment by aendk** [comment] 2021-03-02 19:20
thank for your input. You can consider this issue as done, as its not related to hipSYCL specifically (and you've done more than enough to help me:)  ). I'll close the issue this weekend at the latest.

For completions sake (and in case you are curious), here is an explanation of my workload. 
The workload is database processing, and the kernel-function in hipSYCL is to filter out all unwanted tuples/rows, e.g. for a request of all transactions by customer abc for the year x.
For debugging, I only implemented hardcoded vectors of size 4 yet.
The database table with various different fields is saved in vectors, one for each field(also datatype-entries). Each vector corresponds to a column. So for 4 database entries/rows, there is a year-vector of size 4.
```
  year |   discount |  customer      | price 
   1994|    0.25    |     1          | 55.4
   1999|    0.50    |     5          | 34.7
   2012|    0.10    |     2          | 85.9
   2005|    0.00    |     3          | 22.1
```
saved in a year-, discount-, customer- and price-vector.

This is what created my need to compare a single ```year[0]``` to the ```uint desired_year``` of the database-query, in parallel for, for all rows of the table at the same time.

**Comment by illuhad** [comment] 2021-03-02 19:33
Okay, I think I got it. I think the issue is that you are not looking at a single year vector, but instead at a 1D array of them since you are using a 1D accessor. Therefore, what `year[0]` gives you is not a single number, but a four-component `vec`. To actually get the first year number you need to use `year[0][0]` or `year[0].x()`.
What you actually want to do is to
1. create one 1D accessor per column, e.g. years, discounts, ...
2. In each parallel work item with id `i`, look at `years[i] == desired_year` (which will work because `years[i]` is now just a number and not a `vec`)
3. Store somewhere the result of your filter.

**Comment by illuhad** [comment] 2021-03-11 12:19
Closing as I assume this was solved.

**Closed as completed by illuhad** 2021-03-11 12:19 UTC
Labels: discussion
