### ISSUE TITLE
Add -v / --version arguments to the syclcc executable

### ISSUE THREAD

**Issue by krasznaa** [AdaptiveCpp/AdaptiveCpp#653] opened 2021-10-28 12:42 UTC
## Describe the motivation for the feature request

CMake code in some situations identifies compilers from some characteristic printout in their self-description. This can help generic CMake code figure out what settings to use for a compiler.

## Describe the solution you'd like

It would be nice if the `syclcc` command could react to the `-v` / `--version` command line arguments. And print something that would make it possible to identify the compiler from those messages.

## If applicable, describe alternatives you've considered

With CMake it's also possible to just compile some simple code, which would report about the values of certain pre-defined macros. This is how more detailed information about a compiler is gathered.

But to even get to a point where CMake would know how to compile a simple executable with `syclcc`, it would be good to know already that we're dealing with "some version of" hipSYCL. For which a call to `<compiler> -v` would be ideal.

This is not a make-or-break requirement though. The compiler type could potentially be discovered in other ways as well. But since a "version printout" from the main executable would seem like a good feature anyway, I thought I'd open this ticket. :wink:

## Additional context

N/A

**Comment by illuhad** [comment] 2021-10-28 12:52
This information is provided in the cmake package version file, which cmake will utilize if you `find_package(hipSYCL)`.
It's not clear to me why this is required given that we already have cmake integration using `find_package(hipSYCL)` and `add_sycl_to_target()`?

**Comment by krasznaa** [comment] 2021-10-28 13:03
:confused: hipSYCL is not the only game in town. It's nice that the project comes with its own CMake configuration, it really is. But I do not plan to build my own project's configuration around that...

But just like in my other ticket, the background that I gave is pretty independent of my feature request. Is there any opposition to having `syclcc` print some nice version information with `syclcc -v`? :confused:

**Comment by illuhad** [comment] 2021-10-28 14:12
> confused hipSYCL is not the only game in town. It's nice that the project comes with its own CMake configuration, it really is. But I do not plan to build my own project's configuration around that...

I am pointing that out because if this is about coming up with a common cmake infrastructure for hipSYCL and other SYCL implementations like DPC++, the better approach is to use the `add_sycl_to_target()` interface which is supported by every SYCL implementation except for DPC++, and it's trivial to implement it for DPC++ as a user.
Not only is this more portable, it is also a far superior approach compared to e.g. using `CMAKE_CXX_COMPILER=syclcc` because hipSYCL supports a wide variety of compilation flows, some of which may imply that `syclcc` switches compilers depending on the specified target which cmake absolutely does not like if the `CMAKE_CXX_COMPILER` changes its identification. This is why we are hesitant to support such project configurations, and if you go this route we may be unable to support issues that arise as a consequence.

Please understand that I'm not trying to make your life difficult, I'm trying to provide solutions that will ultimately really give you a good experience, and I suspect that the path that you are currently on will not result in a good experience :)

I don't think we can override `-v` because this flag might be used by build systems to adapt to the compiler (e.g. clang) underneath hipSYCL. If you just want to check if the command is `syclcc`, you can just invoke it without arguments in which case it will print the `syclcc` help message which can be used for identification. If you want more in depth information we could introduce something like a `--hipsycl-version`.

Also, I'm a bit surprised that you consider using `find_package(hipSYCL)` to imply that you have to "build my own project's configuration around that". `find_package()` is common practice when working with cmake.

**Comment by krasznaa** [comment] 2021-10-28 16:14
I doubt that anybody would be using `-v` with `syclcc`. Since it doesn't do anything useful at the moment.

```
[bash][Legolas]:oneAPI > /opt/hipSYCL/bin/syclcc -v
Traceback (most recent call last):
  File "/opt/hipSYCL/bin/syclcc", line 431, in targets
    raw_target_string = self._retrieve_option("targets")
  File "/opt/hipSYCL/bin/syclcc", line 380, in _retrieve_option
    raise OptionNotSet("Required command line argument {} or environment variable {} not specified".format(
__main__.OptionNotSet: Required command line argument --hipsycl-targets or environment variable HIPSYCL_TARGETS not specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hipSYCL/bin/syclcc", line 447, in targets
    target_arch = self._retrieve_option("gpu-arch")
  File "/opt/hipSYCL/bin/syclcc", line 380, in _retrieve_option
    raise OptionNotSet("Required command line argument {} or environment variable {} not specified".format(
__main__.OptionNotSet: Required command line argument --hipsycl-gpu-arch or environment variable HIPSYCL_GPU_ARCH not specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hipSYCL/bin/syclcc", line 1099, in <module>
    c = compiler(config)
  File "/opt/hipSYCL/bin/syclcc", line 915, in __init__
    self._targets = config.targets
  File "/opt/hipSYCL/bin/syclcc", line 453, in targets
    raise OptionNotSet("Neither a --hipsycl-targets specification "
__main__.OptionNotSet: Neither a --hipsycl-targets specification nor the legacy combination of --hipsycl-platform and --hipsycl-gpu-arch was provided
[bash][Legolas]:oneAPI >
```

I do not want to open a faith way over CMake usage. I've heard from Intel developers that people were against implementing the same type of support in CMake that exists for CUDA and HIP. I assumed the opposition was from the CMake developers themselves. But apparently not... :confused:

**Comment by illuhad** [comment] 2021-10-28 16:27
> I doubt that anybody would be using -v with syclcc. Since it doesn't do anything useful at the moment.

Well you still need to set mandatory hipSYCL arguments such as `--hipsycl-targets`. These would however be set by your environment. Currently `syclcc` follows the strict logic that all hipSYCL arguments are prefixed by `--hipsycl-`, and all other arguments affect the underlying compiler.
Since hipSYCL is a layer on top of other compilers (unlike e.g. DPC++) this makes a lot of sense, since you could also be interested in knowing what the version or identification of the actual compiler is that hipSYCL invokes.

> I do not want to open a faith way over CMake usage. I've heard from Intel developers that people were against implementing the same type of support in CMake that exists for CUDA and HIP. I assumed the opposition was from the CMake developers themselves. But apparently not... confused

What you heard... is a bit misleading. Nobody was against top-tier SYCL support in upstream cmake. The issue is that Intel's proposal was really only tailored around their implementation, and did not take into account Codeplay or hipSYCL use cases. Additionally, SYCL is far more general and flexible compared to CUDA or HIP, so the same approach that works there is not necessarily a good match for SYCL. My take is that the `add_sycl_to_target()` cmake infrastructure is well established, and already was before DPC++ came around (after all, DPC++ is the youngest among ComputeCpp, triSYCL, hipSYCL) and it's really DPC++ that's not supporting established conventions that they could easily support.

**Comment by illuhad** [comment] 2022-02-11 03:25
There is now `--hipsycl-version`, so closing this issue.

**Closed as completed by illuhad** 2022-02-11 03:25 UTC
Labels: enhancement
