### ISSUE TITLE
Build error with ROCm 5.0

### ISSUE THREAD

**Issue by vitduck** [AdaptiveCpp/AdaptiveCpp#746] opened 2022-06-01 03:53 UTC
**Bug summary**
hipSYCL source build fails when using ROCm-distributed  Clang compiler

**To Reproduce**
```
cmake .. \
    -DROCM_PATH=/opt/rocm-5.0  \
    -DBOOST_ROOT=/global/home/tyhong/build/opt/boost \
    -DCMAKE_C_COMPILER=clang \
   -DCMAKE_CXX_COMPILER=clang++ \ 
    -DLLVM_DIR=/opt/rocm-5.0.0/llvm/lib/cmake/llvm \
    -DWITH_ACCELERATED_CPU=OFF 
```
```
-- The C compiler identification is Clang 14.0.0
-- The CXX compiler identification is Clang 14.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rocm-5.0.0/llvm/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rocm-5.0.0/llvm/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /global/home/tyhong/build/opt/boost/include (found version "1.68.0") found components: context fiber thread chrono system date_time atomic 
-- Could not find HIP cmake integration, falling back to finding hipcc
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Building hipSYCL against LLVM configured from /opt/rocm-5.0.0/llvm/lib/cmake/llvm/
-- Selecting clang: /opt/rocm-5.0.0/llvm/bin/clang++
-- Using clang include directory: /opt/rocm-5.0.0/llvm/lib/clang/14.0.0/include/..
-- Found OpenMP_C: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /global/home/tyhong/build/src/hipSYCL-0.9.2/build
```

```-DWITH_ACCELERATED_CPU=OFF``` was used following the suggestion in  #709

**Describe your setup**
* hipSYCL 0.9.2 (Feb 15)
* AMD Accelerator Cloud 
   * AMD clang version 14.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.0.0)
   * ROCm version 5.0 
   * gcc version 8.5 

**Additional context**
AMD Accelerator Cloud provides gcc 7.5, which lead to an error due ```std::filesystem``` was not implemented. 
I updated gcc tool chain to 8.5. The error message  is follow: 
```
In file included from /global/home/tyhong/build/src/hipSYCL-0.9.2/src/runtime/backend_loader.cpp:29:
In file included from /global/home/tyhong/build/src/hipSYCL-0.9.2/include/hipSYCL/runtime/backend_loader.hpp:32:
In file included from /global/home/tyhong/build/opt/gcc/include/c++/8.5.0/string:41:
In file included from /global/home/tyhong/build/opt/gcc/include/c++/8.5.0/bits/allocator.h:46:
In file included from /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/x86_64-linux-gnu/c++/7.5.0/bits/c++allocator.h:33:
In file included from /global/home/tyhong/build/opt/gcc/include/c++/8.5.0/ext/new_allocator.h:33:
In file included from /global/home/tyhong/build/opt/gcc/include/c++/8.5.0/new:40:
/global/home/tyhong/build/opt/gcc/include/c++/8.5.0/exception:101:3: error: unknown type name '_GLIBCXX17_DEPRECATED'
  _GLIBCXX17_DEPRECATED
  ^
In file included from /global/home/tyhong/build/src/hipSYCL-0.9.2/src/runtime/backend_loader.cpp:29:
In file included from /global/home/tyhong/build/src/hipSYCL-0.9.2/include/hipSYCL/runtime/backend_loader.hpp:32:
In file included from /global/home/tyhong/build/opt/gcc/include/c++/8.5.0/string:52:
In file included from /global/home/tyhong/build/opt/gcc/include/c++/8.5.0/bits/basic_string.h:48:
In file included from /global/home/tyhong/build/opt/gcc/include/c++/8.5.0/string_view:43:
/global/home/tyhong/build/opt/gcc/include/c++/8.5.0/bits/functional_hash.h:52:38: error: expected ';' at end of declaration list
      typedef _Result     result_type _GLIBCXX17_DEPRECATED;
                                     ^
/global/home/tyhong/build/opt/gcc/include/c++/8.5.0/bits/functional_hash.h:53:38: error: expected ';' at end of declaration list
      typedef _Arg      argument_type _GLIBCXX17_DEPRECATED;
                                     ^
3 errors generated.
```
* CPATH contains ``` /global/home/tyhong/build/opt/gcc/include/c++/8.5.0/``` which should allow  ```_GLIBCXX17_DEPRECATED``` to be loaded from sub directory ```bits/c++config.h```
* The ';' related error should have been mitigated by already included ```--std=c++17``` flags

The installation guide does not mentioned any specific gcc requirement. Should I continue to bump gcc to higher version ? 

Regards.

**Comment by vitduck** [comment] 2022-06-22 02:40
For reference, this issue was due to gcc toolchain. 
I was able to compile hipSYCL using the following cmake command in case gcc 9.4 was built from source separately. 
```
cmake .. \
    -DCMAKE_INSTALL_PREFIX=[...] \
    -DCMAKE_C_COMPILER=amdclang \
    -DCMAKE_CXX_COMPILER=amdclang++ \
    -DROCM_PATH=/opt/rocm \
    -DBOOST_ROOT=$HOME/build/opt/boost \
    -DCMAKE_CXX_FLAGS="--gcc-toolchain=[...]/build/opt/gcc" \
    -DLLVM_DIR=/opt/rocm/llvm/lib/cmake \
    -DWITH_ACCELERATED_CPU=OFF  \
```

Likewise, for ```vecadd.cpp``` example: 
```
export HIPSYCL_ROCM_CXX_FLAGS=--gcc-toolchain=/global/home/tyhong/build/opt/gcc

syclcc \
    -O2 \
    --hipsycl-targets=hip:gfx90a \
    --hipsycl-clang=/opt/rocm/llvm/bin/amdclang++ \
    --hipsycl-rocm-path=/opt/rocm \
    vecadd.cpp
```

However, the executable emit the following error: 
```
"Cannot find Symbol"
Aborted
```

System information: 
```
*******                  
Agent 9                  
*******                  
  Name:                    gfx90a                             
  Uuid:                    GPU-6de8c605c2212805               
  Marketing Name:                                             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    8                                  
  Device Type:             GPU               
```

I was able to compile the SYCL port of GROMACS, but ```gmx``` also emitted ```Cannot find Symbol``` error.
Please kindly advise how to debug this issue.

**Comment by illuhad** [comment] 2022-06-22 19:37
I'm not sure what is going on (probably some ABI issue due to different toolchains or so). We should attempt to find out what symbols cannot be found. Is there any mention of libraries not found when running `ldd` with any of the libraries in `$HIPSYCL_INSTALL_PREFIX/lib` and its subdirectories?

**Comment by vitduck** [comment] 2022-06-23 00:54
Per your suggestion, below are the ldd result of libraries under ```$HIPSYCL_INSTALL_PREFIX/lib```
```
$ ldd libhipSYCL_clang.so 
        linux-vdso.so.1 (0x00007ffc8bb7d000)
        libboost_fiber.so.1.76.0 => /global/home/tyhong/build/opt/boost/lib/libboost_fiber.so.1.76.0 (0x00007fab2c8f8000)
        libboost_context.so.1.76.0 => /global/home/tyhong/build/opt/boost/lib/libboost_context.so.1.76.0 (0x00007fab2c6f5000)
        libboost_filesystem.so.1.76.0 => /global/home/tyhong/build/opt/boost/lib/libboost_filesystem.so.1.76.0 (0x00007fab2c4d7000)
        libstdc++.so.6 => /global/home/tyhong/build/opt/gcc/lib64/libstdc++.so.6 (0x00007fab2c0f7000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fab2bd59000)
        libgcc_s.so.1 => /global/home/tyhong/build/opt/gcc/lib64/libgcc_s.so.1 (0x00007fab2bb41000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fab2b750000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fab2b548000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fab2b329000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fab2cb0b000)
```
```
$ ldd libhipSYCL-rt.so
        linux-vdso.so.1 (0x00007ffe1d7be000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6cbbf99000)
        libstdc++.so.6 => /global/home/tyhong/build/opt/gcc/lib64/libstdc++.so.6 (0x00007f6cbbbb9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6cbb81b000)
        libgcc_s.so.1 => /global/home/tyhong/build/opt/gcc/lib64/libgcc_s.so.1 (0x00007f6cbb603000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6cbb212000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6cbc19d000)
```
```
$ ldd librt-backend-hip.so
        linux-vdso.so.1 (0x00007ffe5535a000)
        libstdc++.so.6 => /global/home/tyhong/build/opt/gcc/lib64/libstdc++.so.6 (0x00007f081927d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0818edf000)
        libgcc_s.so.1 => /global/home/tyhong/build/opt/gcc/lib64/libgcc_s.so.1 (0x00007f0818cc7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f08188d6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f081965d000)
```
```
$ ldd librt-backend-omp.so
        linux-vdso.so.1 (0x00007ffea1fd8000)
        libhipSYCL-rt.so => /global/home/tyhong/build/opt/hipSYCL/lib/libhipSYCL-rt.so (0x00007f0494331000)
        libomp.so => /opt/rocm/llvm/lib/libomp.so (0x00007f0494243000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0493f49000)
        libstdc++.so.6 => /global/home/tyhong/build/opt/gcc/lib64/libstdc++.so.6 (0x00007f0493b69000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f04937cb000)
        libgcc_s.so.1 => /global/home/tyhong/build/opt/gcc/lib64/libgcc_s.so.1 (0x00007f04935b3000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f04931c2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0494168000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0492fbe000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0492db6000)
```
At first glance, I don't see any missing symbol from .so file. The binary was linked against: 
```
      libhipSYCL-rt.so => /global/home/tyhong/build/opt/hipSYCL/lib/libhipSYCL-rt.so (0x00007f8d5bca6000)
      libamdhip64.so.5 => /opt/rocm/hip/lib/libamdhip64.so.5 (0x00007f8d5abfd000)
```
Though ```libhipSYCL-rt.so``` is not linked against ```librt-backend-hip.so```. 
I wonder if this is an expected behavior.

**Comment by illuhad** [comment] 2022-06-23 01:30
Yes, that looks fine. `libhipSYCL-rt.so` is not linked against the backend plugins, as they are loaded dynamically at runtime using `dlopen()`. So this is fine too.
Do you also see the symbol error if you compile a simple test program for a different backend, e.g. `--hipsycl-targets=omp`?

**Comment by vitduck** [comment] 2022-06-23 02:07
I compiled for omp backend as follow: 
```
export HIPSYCL_OMP_CXX_FLAGS=--gcc-toolchain=/global/home/tyhong/build/opt/gcc

syclcc \
    -O2 \
    --hipsycl-targets=omp \
    --hipsycl-clang=/opt/rocm/llvm/bin/amdclang++ \
    vecadd.cpp
```
The correct result was obtained: 
```
[hipSYCL Warning] backend_loader: Could not load backend plugin: /global/home/tyhong/build/opt/hipSYCL/lib/hipSYCL/librt-backend-hip.so
[hipSYCL Warning] /global/home/tyhong/build/opt/hipSYCL/lib/hipSYCL/librt-backend-hip.so: undefined symbol: hipEventDestroy
Result:
0
4
0
8
0
```

If it may help, I attached here the debug message with ```HIPSYCL_DEBUG_LEVEL=4``` for hip backend
```
[hipSYCL Info] backend_loader: Searching path for backend libs: '"/global/home/tyhong/build/opt/hipSYCL/lib/hipSYCL"'
[hipSYCL Info] backend_loader: Successfully opened plugin: "/global/home/tyhong/build/opt/hipSYCL/lib/hipSYCL/librt-backend-omp.so" for backend 'omp'
[hipSYCL Info] backend_loader: Successfully opened plugin: "/global/home/tyhong/build/opt/hipSYCL/lib/hipSYCL/librt-backend-hip.so" for backend 'hip'
...
[hipSYCL Info] Discovered devices from backend 'OpenMP':
[hipSYCL Info]   device 0:
[hipSYCL Info]     vendor: the hipSYCL project
[hipSYCL Info]     name: hipSYCL OpenMP host device
[hipSYCL Info] Discovered devices from backend 'HIP':
[hipSYCL Info]   device 0:
[hipSYCL Info]     vendor: AMD
[hipSYCL Info]     name:
[hipSYCL Info]   device 1:
[hipSYCL Info]     vendor: AMD
[hipSYCL Info]     name:
[hipSYCL Info]   device 2:
[hipSYCL Info]     vendor: AMD
[hipSYCL Info]     name:
[hipSYCL Info]   device 3:
[hipSYCL Info]     vendor: AMD
[hipSYCL Info]     name:
...
[hipSYCL Info] buffer_memory_requirement: Attempting to initialize embedded pointers for requirement 0x12698c0
[hipSYCL Info] Identified embedded pointer with uid 7629112841450649061-16867770591382048098 in kernel blob, setting to 0x7fd742e09000
[hipSYCL Info] buffer_memory_requirement: Attempting to initialize embedded pointers for requirement 0x1269a90
[hipSYCL Info] Identified embedded pointer with uid 8421768372517942010-9229585356580169570 in kernel blob, setting to 0x7fd742e0a000
[hipSYCL Info] buffer_memory_requirement: Attempting to initialize embedded pointers for requirement 0x1269c90
[hipSYCL Info] Identified embedded pointer with uid 3882116854743891538-5338635806676060002 in kernel blob, setting to 0x7fd742e0b000
```
So both omp and hip backend was loaded. 
For hip, 4 GPUs was regconized as well. The symbol error happens after embbeded pointers initialization attempt. 

[debug.txt](https://github.com/illuhad/hipSYCL/files/8962882/debug.txt)

**Comment by illuhad** [comment] 2022-06-23 18:14
Okay, it sets the embedded pointers before actually invoking the kernel. Since it seems to work fine for OpenMP, I believe the issue is related to invoking the HIP kernel.
Can you confirm that you can execute HIP kernels from regular HIP applications?
There was a bug in 0.9.2 release that has since been fixed on the develop branch, which causes a potential launch failure for unnamed kernel lambdas. Do you have unnamed lambda kernels in your code? If so, please try with the latest hipSYCL from the `develop` branch.

**Comment by vitduck** [comment] 2022-06-24 03:58
I used vector addition example from the hipSYCL repo itself. 
```
cgh.parallel_for<class vector_add>(work_items, [=] (cl::sycl::id<1> tid) {
    access_c[tid] = access_a[tid] + access_b[tid];
});
```
So this issue is unlikely due to an unamed lambda. 

In any case, I had tried the latest commit as you suggested. The hip kernel was then successfully launched.
```
...
[hipSYCL Info] buffer_memory_requirement: Attempting to initialize embedded pointers for requirement 0x1cb3d20
[hipSYCL Info] Identified embedded pointer with uid 12367081715724995148-16651717656192299032 in kernel blob, setting to 0x7f009760b000
[hipSYCL Info] dag_manager [async]: Submitting node to scheduler!
[hipSYCL Info] dag_direct_scheduler: Setting device data pointer of requirement node MEM_REQ: R host_buffer {0, 0, 0}+{1, 1, 5} #4 to 0x1e7fa60
[hipSYCL Info] multi_queue_executor: Processing node 0x1c15100 with 1 non-virtual requirement(s) and 1 direct requirement(s).
[hipSYCL Info]  --> Synchronizes with other queue for node: 0x1c14da0 lane = 2
[hipSYCL Info] multi_queue_executor: Dispatching to lane 1: Memcpy: ROCm-Device0 #4 {0, 0, 0}+{1, 1, 5}-->CPU-Device0 #4 {0, 0, 0}+{1, 1, 5}{1, 1, 5}
[hipSYCL Info] dag_manager [async]: DAG flush complete.
[hipSYCL Info] buffer_impl::~buffer_impl: Waiting for operations to complete...
[hipSYCL Info] buffer_impl::~buffer_impl: Waiting for operations to complete...
Result: 
0
4
0
8
0
```
Likewise, I was able to re-compile GROMACS and perform a test run.

In Intel-LLVM there is an debug environment variable that concisely shows which backend and devices are selected, i.e. 
```
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_opencl.so
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_level_zero.so
SYCL_PI_TRACE[all]: Selected device ->
SYCL_PI_TRACE[all]:   platform: Intel(R) Level-Zero
SYCL_PI_TRACE[all]:   device: Intel(R) Iris(R) Xe MAX Graphics [0x4905]
```
From hipSYCL debug messages, it is not immediately clear to me which device is selected. 
Of course, one can deduce it from the memcpy message regarding data transfer from CPU to ROCM-devices. 

Is there a similar environment variable that allow us to confirm the execution on GPU ? 

Thanks.

**Comment by illuhad** [comment] 2022-06-24 15:17
> So this issue is unlikely due to an unamed lambda.
> In any case, I had tried the latest commit as you suggested. The hip kernel was then successfully launched.

Thanks for the feedback. It might still be due to the bug, since the lambda name in this example code is not declared globally. The issue is due to inconsistent enumeration of the lambdas (which enters the mangled kernel name) across host and device pass. Since the kernel name is defined inside the submit lambda, the enumeration of the submit lambda might still enter the kernel name.

> Likewise, I was able to re-compile GROMACS and perform a test run.

Excellent. Please be advised that optimization of hipSYCL for Gromacs is work in progress and still incomplete.

> From hipSYCL debug messages, it is not immediately clear to me which device is selected.
> Of course, one can deduce it from the memcpy message regarding data transfer from CPU to ROCM-devices.
> Is there a similar environment variable that allow us to confirm the execution on GPU ?
> Thanks.

Not really, because in hipSYCL device selectors operate directly inside the SYCL interface, so the hipSYCL runtime (which prints these debug messages) does not handle device selection and therefore does not see the device selection process.

However, we make the following guarantees:
* a `gpu_selector` will throw an exception if a GPU could not be selected
* When multiple device backends are available, the environment variable `HIPSYCL_VISIBILITY_MASK` can be used to only selectively make backends available. However, you will not be able to disable the CPU backend in this way since it is always needed to satisfy the requirement of the SYCL specification that the default selector should never fail (e.g. if no GPUs can be detected in the system).
* a default selector will always select a GPU, if the runtime sees one (can be seen with `HIPSYCL_DEBUG_LEVEL=3` right at the start) and the corresponding backend has been targeted.

**Comment by vitduck** [comment] 2022-06-28 08:12
Thanks for your insights regarding lambda. 

We are only doing a performance survey of various HPC applications on AMD GPUs. 
There is still long way to go for Gromacs in term of performance optimization and verification. But it is nevertheless a good start. 

Regarding the device selector, the explanation is also very clear to me. 
Unless you have further comment, please close this issue. 

Thank you for your time.

**Closed as completed** 2022-06-28 11:03 UTC
Labels: bug
