### ISSUE TITLE
error: no member named 'div_t' in the global namespace

### ISSUE THREAD

**Issue by Helena2007** [AdaptiveCpp/AdaptiveCpp#1415] opened 2024-03-23 09:09 UTC
While trying to run the example bruteforce_nbody using CMake integration with AdaptiveCpp.
when trying to run make install I got the following error. I am using ubuntu 22.04, cuda-11.7 and clang-14.0.0
In file included from <built-in>:1:
In file included from /usr/lib/llvm-14/lib/clang/14.0.0/include/__clang_cuda_runtime_wrapper.h:41:
In file included from /usr/include/cuda/std/detail/libcxx/include/cmath:305:
In file included from /usr/include/cuda/std/detail/libcxx/include/math.h:301:
In file included from /usr/include/cuda/std/detail/libcxx/include/stdlib.h:20:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/stdlib.h:36:
/usr/include/cuda/std/detail/libcxx/include/cstdlib:104:9: error: no member named 'div_t' in the global namespace
using ::div_t;
      ~~^
/usr/include/cuda/std/detail/libcxx/include/cstdlib:105:9: error: no member named 'ldiv_t' in the global namespace
using ::ldiv_t;
      ~~^
/usr/include/cuda/std/detail/libcxx/include/cstdlib:107:9: error: no member named 'lldiv_t' in the global namespace
using ::lldiv_t;
      ~~^
/usr/include/cuda/std/detail/libcxx/include/cstdlib:109:9: error: no member named 'atof' in the global namespace
using ::atof;
      ~~^
/usr/include/cuda/std/detail/libcxx/include/cstdlib:110:9: error: no member named 'atoi' in the global namespace
using ::atoi;

**Comment by illuhad** [comment] 2024-03-23 15:41
This does not look like an AdaptiveCpp problem, but some incompatibility between your clang version, CUDA version, and libstdc++ version. Also, clang 14 may not support CUDA installations as packaged by some Linux distributions (i.e. the CUDA SDK being scattered in `/usr` or `/usr/local`) as described here: https://releases.llvm.org/14.0.0/docs/CompileCudaWithLLVM.html. So you might have to install CUDA using the official NVIDIA installer.

In CI we test clang 14 only with CUDA 11.0.2. So you might have to upgrade clang or downgrade CUDA.

All of this only matters for the old interoperability-focused SMCP compilers (`--acpp-targets=cuda`), which you seem to be using and which rely on the clang CUDA toolchain.

You can avoid these issues by just using AdaptiveCpp's main compiler, the generic SSCP compiler (`--acpp-targets=generic`). It compiles faster and usually generates faster binaries since it does a lot of additional optimizations. It does not need the clang CUDA toolchain and is hence immune by design to such compatibility issues.

**Comment by Helena2007** [comment] 2024-03-27 11:06
Ubuntu 22.04 does not support cuda version below 11.7. So, upgraded clang compiler to clang-15. But still the error persists.

**Comment by illuhad** [comment] 2024-03-27 14:24
> Ubuntu 22.04 does not support cuda version below 11.7

No that doesn't seem right. Where does it say that? In CI we also have Ubuntu 22.04 with CUDA 11.0 which works just fine:
https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/.github/workflows/linux-self-hosted.yml

How are you installing CUDA? If you are installing from Ubuntu package repositories, that might not work as I had mentioned. Clang does not like CUDA installations the way they are packaged by distributions. You may have to run the official NVIDIA installer for the userspace SDK. The kernel driver can be installed from packages, as long as it is version-compatible with the userspace components.

EDIT: Can you please provide more information on how you have installed CUDA and AdaptiveCpp? Ideally the exact commands.

**Comment by Helena2007** [comment] 2024-03-28 06:03
Installed AdaptiveCpp following the instructions : https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/doc/installing.md#a-standard-installation
I have tried to install CUDA from CUDA Toolkit Archive
https://developer.nvidia.com/cuda-11-5-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu
Here, CUDA 11.7 is the minimum supported version for Ubuntu 22.04

**Comment by illuhad** [comment] 2024-04-01 01:16
Select Ubuntu 20.04 and choose the runfile download. I'm not aware of any compatibility issues in Ubuntu 22.04 with CUDA 11.x for the components that AdaptiveCpp actually needs.

EDIT: You may want to pass `--toolkit --no-man-page --no-drm --no-opengl-libs --installpath=/your/desired/cuda/install/path` or similar to the CUDA installer to avoid it messing too much with drivers etc.

(Or again, just use the default compiler `--acpp-targets=generic`  which is going to be superior in the vast majority of cases anyway and should be free of such compatibility issues)

**Comment by illuhad** [comment] 2024-04-12 05:27
Closing because the issue was presumably solved.

**Closed as completed by illuhad** 2024-04-12 05:27 UTC
Labels: discussion
