### ISSUE TITLE
openmp in opensycl

### ISSUE THREAD

**Issue by garadeaniket** [AdaptiveCpp/AdaptiveCpp#1025] opened 2023-04-25 15:19 UTC
1) can anyone please explain how the openmp code is identified and executed by runtime in opensycl?
2) is the openmp code is converted into sycl code in opensycl?

**Comment by illuhad** [comment] 2023-04-25 15:29
Closing as a duplicate of the discussion here: https://github.com/OpenSYCL/OpenSYCL/discussions/1024

**Closed as completed by illuhad** 2023-04-25 15:29 UTC
Labels: discussion
