### ISSUE TITLE
How to Build LULESH stdpar Using acpp

### ISSUE THREAD

**Issue by Ehu1** [AdaptiveCpp/AdaptiveCpp#1597] opened 2024-11-13 03:51 UTC
I encountered a build failure using the following Makefile
```
# Build with nvc++, with parallel algorithm support turned on.

SHELL = /bin/sh
.SUFFIXES: .cc .o

LULESH_EXEC = lulesh2.0

CXX = acpp

SOURCES2.0 = \
	lulesh.cc \
	lulesh-comm.cc \
	lulesh-viz.cc \
	lulesh-util.cc \
	lulesh-init.cc
OBJECTS2.0 = $(SOURCES2.0:.cc=.o)

CXXFLAGS = -O2 --acpp-stdpar --acpp-save-temps -I/home/yanyu/xyh/AdaptiveCpp/install/include/tbb/ -L/home/yanyu/xyh/AdaptiveCpp/install/lib/ -ltbb -DUSE_MPI=0
LDFLAGS = $(CXXFLAGS) 

%.o: ../src/%.cc ../src/lulesh.h
	@echo "Building $<"
	$(CXX) -c $(CXXFLAGS) -o $@  $<

all: $(LULESH_EXEC)

$(LULESH_EXEC): $(OBJECTS2.0)
	@echo "Linking"
	$(CXX) $(OBJECTS2.0) $(LDFLAGS) -lm -o $@

run: $(LULESH_EXEC)
	./lulesh2.0 -p -s 150

clean:
	/bin/rm -f *.o *~ $(OBJECTS) $(LULESH_EXEC)
	/bin/rm -rf *.dSYM

```

```
AdaptiveCpp Warning] kernel_cache: This application run has resulted in new binaries being JIT-compiled. This indicates that the runtime optimization process has not yet reached peak performance. You may want to run the application again until this warning no longer appears to achieve optimal performance.

[AdaptiveCpp Error] from /home/yanyu/xyh/AdaptiveCpp/src/runtime/cuda/cuda_code_object.cpp:96 @ build_cuda_module_from_ptx(): cuda_executable_object: Could not load module, CUDA JIT log: ptxas application ptx input, line 108; error   : Call has wrong number of parameters
ptxas application ptx input, line 165; error   : Call has wrong number of parameters
ptxas application ptx input, line 220; error   : Call has wrong number of parameters
ptxas application ptx input, line 277; error   : Call has wrong number of parameters
ptxas application ptx input, line 332; error   : Call has wrong number of parameters
ptxas application ptx input, line 389; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors (error code = CU:218)

[AdaptiveCpp Error] from /home/yanyu/xyh/AdaptiveCpp/src/runtime/cuda/cuda_queue.cpp:694 @ submit_sscp_kernel_from_code_object(): cuda_queue: Code object construction failed

[AdaptiveCpp Error] from /home/yanyu/xyh/AdaptiveCpp/src/runtime/cuda/cuda_code_object.cpp:96 @ build_cuda_module_from_ptx(): cuda_executable_object: Could not load module, CUDA JIT log: ptxas application ptx input, line 108; error   : Call has wrong number of parameters
ptxas application ptx input, line 165; error   : Call has wrong number of parameters
ptxas application ptx input, line 220; error   : Call has wrong number of parameters
ptxas application ptx input, line 277; error   : Call has wrong number of parameters
ptxas application ptx input, line 332; error   : Call has wrong number of parameters
ptxas application ptx input, line 389; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors (error code = CU:218)

[AdaptiveCpp Error] from /home/yanyu/xyh/AdaptiveCpp/src/runtime/cuda/cuda_queue.cpp:694 @ submit_sscp_kernel_from_code_object(): cuda_queue: Code object construction failed
```

**Comment by Ehu1** [comment] 2024-11-13 03:52
```
AdaptiveCpp Warning] kernel_cache: This application run has resulted in new binaries being JIT-compiled. This indicates that the runtime optimization process has not yet reached peak performance. You may want to run the application again until this warning no longer appears to achieve optimal performance.
[AdaptiveCpp Error] from /home/yanyu/xyh/AdaptiveCpp/src/runtime/cuda/cuda_code_object.cpp:96 @ build_cuda_module_from_ptx(): cuda_executable_object: Could not load module, CUDA JIT log: ptxas application ptx input, line 108; error   : Call has wrong number of parameters
ptxas application ptx input, line 165; error   : Call has wrong number of parameters
ptxas application ptx input, line 220; error   : Call has wrong number of parameters
ptxas application ptx input, line 277; error   : Call has wrong number of parameters
ptxas application ptx input, line 332; error   : Call has wrong number of parameters
ptxas application ptx input, line 389; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors (error code = CU:218)
[AdaptiveCpp Error] from /home/yanyu/xyh/AdaptiveCpp/src/runtime/cuda/cuda_queue.cpp:694 @ submit_sscp_kernel_from_code_object(): cuda_queue: Code object construction failed
[AdaptiveCpp Error] from /home/yanyu/xyh/AdaptiveCpp/src/runtime/cuda/cuda_code_object.cpp:96 @ build_cuda_module_from_ptx(): cuda_executable_object: Could not load module, CUDA JIT log: ptxas application ptx input, line 108; error   : Call has wrong number of parameters
ptxas application ptx input, line 165; error   : Call has wrong number of parameters
ptxas application ptx input, line 220; error   : Call has wrong number of parameters
ptxas application ptx input, line 277; error   : Call has wrong number of parameters
ptxas application ptx input, line 332; error   : Call has wrong number of parameters
ptxas application ptx input, line 389; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors (error code = CU:218)
[AdaptiveCpp Error] from /home/yanyu/xyh/AdaptiveCpp/src/runtime/cuda/cuda_queue.cpp:694 @ submit_sscp_kernel_from_code_object(): cuda_queue: Code object construction failed

```

**Comment by Ehu1** [comment] 2024-11-13 03:58
However, I am able to successfully run simple stdpar code, but running LULESH fails.

**Comment by illuhad** [comment] 2024-11-13 04:55
Hi,

I regularly run LULESH for regression testing and performance analysis. The upstream LULESH code was designed for nvc++ and uses some features in device code for debugging like `printf` that are not portable to other hardware and can cause such JIT issues. Also, it uses `std::execution::par` instead of `par_unseq` which only very recently AdaptiveCpp versions offload, and only to NVIDIA GPUs with strong independent forward progress guarantees (Volta and newer).

Please try my fork which implements some minor changes to address these issues (`par_unseq` instead of `par`, no `printf` in kernels, some changes that are no longer necessary): https://github.com/illuhad/LULESH/tree/2.0.2-dev

Note that LULESH is *massively* latency-bound. For best performance, please disable AdaptiveCpp automatic prefetching which, while normally helpful, due to LULESH's design mainly just adds additional latency: `ACPP_STDPAR_PREFETCH_MODE=never`.

Should you also want to run on discrete Intel GPUs (iGPUs and NVIDIA or AMD hardware are fine), please disable the memory pool by setting pool size to zero (`ACPP_STDPAR_MEM_POOL_SIZE=0`). Please do not do this on other hardware as the memory pool is a crucial performance optimization.

On NVIDIA GPUs, the expected result is that AdaptiveCpp outperforms nvc++ for all problem sizes. With data from my paper https://dl.acm.org/doi/10.1145/3648115.3648117 on an NVIDIA A100:

![lulesh_a100](https://github.com/user-attachments/assets/6d0b85ca-39da-4833-958a-af5b5b5d1840)

**Comment by Ehu1** [comment] 2024-11-14 10:41
> Hi,
> 
> I regularly run LULESH for regression testing and performance analysis. The upstream LULESH code was designed for nvc++ and uses some features in device code for debugging like `printf` that are not portable to other hardware and can cause such JIT issues. Also, it uses `std::execution::par` instead of `par_unseq` which only very recently AdaptiveCpp versions offload, and only to NVIDIA GPUs with strong independent forward progress guarantees (Volta and newer).
> 
> Please try my fork which implements some minor changes to address these issues (`par_unseq` instead of `par`, no `printf` in kernels, some changes that are no longer necessary): https://github.com/illuhad/LULESH/tree/2.0.2-dev
> 
> Note that LULESH is _massively_ latency-bound. For best performance, please disable AdaptiveCpp automatic prefetching which, while normally helpful, due to LULESH's design mainly just adds additional latency: `ACPP_STDPAR_PREFETCH_MODE=never`.
> 
> Should you also want to run on discrete Intel GPUs (iGPUs and NVIDIA or AMD hardware are fine), please disable the memory pool by setting pool size to zero (`ACPP_STDPAR_MEM_POOL_SIZE=0`). Please do not do this on other hardware as the memory pool is a crucial performance optimization.
> 
> On NVIDIA GPUs, the expected result is that AdaptiveCpp outperforms nvc++ for all problem sizes. With data from my paper https://dl.acm.org/doi/10.1145/3648115.3648117 on an NVIDIA A100:
> 
> ![lulesh_a100](https://private-user-images.githubusercontent.com/11861762/385591637-6d0b85ca-39da-4833-958a-af5b5b5d1840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODA4MzAsIm5iZiI6MTczMTU4MDUzMCwicGF0aCI6Ii8xMTg2MTc2Mi8zODU1OTE2MzctNmQwYjg1Y2EtMzlkYS00ODMzLTk1OGEtYWY1YjViNWQxODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwMzUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwN2M4OTQ3NzdkMTc1MjA2ZDZmOGE5MGY4NWQ1OWMwNGRmOTcxZDhmYzZjMGI0ZWY5NDdjMDkzMjIyN2UwY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BTM6BnXuSsoV9OUsDkDzIE_720jI9KpUd2_yJDNk6w0)

Thank you for your reply, this information is very useful to me. Additionally, I would like to ask you about one detail: will the optional_barrier in several std transform functions in .ll always correspond to a synchronization when JIT compiled?

**Comment by illuhad** [comment] 2024-11-14 14:13
> Thank you for your reply, this information is very useful to me. Additionally, I would like to ask you about one detail: will the optional_barrier in several std transform functions in .ll always correspond to a synchronization when JIT compiled?

You're welcome :) The `optional_barrier` you refer to is there because C++ semantics assume that when a PSTL call has finished, data is available right away without any necessary synchronization:

```c++
std::for_each(par_unseq, begin, end, functor);
// No additional synchronization necessary; we can just access *begin
// and the for_each should be guaranteed to be done at this point
std::cout << *begin << std::endl;
```

Because of this, after submitting work to a GPU, C++ PSTL offloading solutions in principle need to wait for completion after every kernel submission.

However, AdaptiveCpp is the only C++ PSTL offloading compiler that can (within some limits) detect cases where the synchronization is not needed because the difference is not observable. For example, when two PSTL calls directly follow each other without host access in between:
```c++
std::for_each(par_unseq, begin1, end1, f);
// A barrier here would not lead to an observable semantic change,
// so AdaptiveCpp can remove the synchronization between these two
// calls
std::for_each(par_unseq, begin2, end2, f);
```
In this case, `optional_barrier` might be removed from LLVM IR by AdaptiveCpp prior to code generation.

You can find more details in my paper: https://dl.acm.org/doi/10.1145/3648115.3648117

**Comment by Ehu1** [comment] 2024-11-14 15:35
> > Thank you for your reply, this information is very useful to me. Additionally, I would like to ask you about one detail: will the optional_barrier in several std transform functions in .ll always correspond to a synchronization when JIT compiled?
> 
> You're welcome :) The `optional_barrier` you refer to is there because C++ semantics assume that when a PSTL call has finished, data is available right away without any necessary synchronization:
> 
> ```c++
> std::for_each(par_unseq, begin, end, functor);
> // No additional synchronization necessary; we can just access *begin
> // and the for_each should be guaranteed to be done at this point
> std::cout << *begin << std::endl;
> ```
> 
> Because of this, after submitting work to a GPU, C++ PSTL offloading solutions in principle need to wait for completion after every kernel submission.
> 
> However, AdaptiveCpp is the only C++ PSTL offloading compiler that can (within some limits) detect cases where the synchronization is not needed because the difference is not observable. For example, when two PSTL calls directly follow each other without host access in between:
> 
> ```c++
> std::for_each(par_unseq, begin1, end1, f);
> // A barrier here would not lead to an observable semantic change,
> // so AdaptiveCpp can remove the synchronization between these two
> // calls
> std::for_each(par_unseq, begin2, end2, f);
> ```
> 
> In this case, `optional_barrier` might be removed from LLVM IR by AdaptiveCpp prior to code generation.
> 
> You can find more details in my paper: https://dl.acm.org/doi/10.1145/3648115.3648117

I understand this point now; you explained it very patiently. I have read your paper and want to confirm one thing: in LLVM IR, if reducing the calls to `optional_barrier` can lead to performance gains. Is it correct that the optimization for eliminating redundant synchronization in your paper is achieved by directly reducing the number of calls to `optional_barrier` in the IR?

**Comment by illuhad** [comment] 2024-11-14 17:18
Yes, in a way. However, if you  simply count the number of occurences of calls to the the barrier you may find that it actually introduces *more* calls to `optional_barrier` in LLVM IR, but it will actually execute *less*.

This is because what it does is to delay synchronization for as long as possible (potentially merging multiple calls to `optional_barrier`), which requires propagating the barrier across all paths in the control flow graph.

Example:

```c++

std::for_each(begin, end, f);
// The for_each will introduce a call to optional_barrier here.
// The compiler will remove this call, and move it as far along the
// control flow graph as possible.
// optional_barrier();
if(mycondition) {
  std::for_each(begin, end, f);
  // barrier is needed here due to the memory access.
  // However, the barrier of both for_each calls is merged
  // into one here.
  optional_barrier();
  return *begin;
} else if(mycondition2) {
  // need barrier for 1st for_each due to memory access
  optional_barrier();
  return *(begin+1)
} else {
  // need barrier for 1st for_each due to memory access
  optional_barrier();
  return *(begin+2);
}
```

So in this example, you will find three calls to `optional_barrier()` in the IR, but the code will never execute more than one, even if the second for each in `mycondition` is called.

**Comment by illuhad** [comment] 2024-11-25 15:17
Closing because the question seems to be answered.

**Closed as completed by illuhad** 2024-11-25 15:17 UTC
Labels: bug
