### ISSUE TITLE
Missing abs function.

### ISSUE THREAD

**Issue by lfield** [AdaptiveCpp/AdaptiveCpp#366] opened 2020-11-06 16:04 UTC
When I tried to use the abs function cl::sycl::abs, I get the following compile error:
 
`error: no member named 'abs' in namespace 'cl::sycl'; did you mean 'fabs'?`

As far as I can tell this function is part of the 1.2 spec and the same code compiles with ComputeCpp.

**Comment by illuhad** [comment] 2020-11-07 21:03
You're right, it seems that one is still missing (like some other integer functions, e.g. `clz`)

**Comment by lfield** [comment] 2020-11-09 16:20
Is there a conformance test for the 1.2 spec?

**Comment by illuhad** [comment] 2020-11-10 09:13
I assume the SYCL conformance test suite for SYCL 1.2.1 probably tests this, see https://github.com/KhronosGroup/SYCL-CTS

However, I don't usually use it because it requires hacks to get it to work with hipSYCL, mainly because the SYCL-CTS assumes OpenCL (since SYCL 1.2.1 officially requires it) which by design is not available in hipSYCL. Because SYCL 1.2.1 mandates OpenCL, hipSYCL cannot be officially conformant anyway, so I'm happy when we can leave SYCL 1.2.1 behind with SYCL 2020..

**Comment by lfield** [comment] 2020-11-10 09:23
Any ideas on time scales for this fix and SYCL 2020?

**Comment by illuhad** [comment] 2020-11-10 15:04
Well, adding a function like `abs` is in principle not much work (although that part of the code might need some additional refactoring in general).

Not sure what you mean by time scales for SYCL 2020. The SYCL 2020 final specification is not even out yet. You can see the progress of implemented features in hipSYCL here: https://github.com/hipSYCL/featuresupport

I think we will have most of the SYCL 2020 key features relatively quickly, but I don't think I can reasonably comment on full conformance (and to my knowledge, no other implementation has given a fixed date either). 

While I would love to see hipSYCL being fully conformant one day, full conformance requires a *lot* of attention to the smallest  details that most users might not even care about, so it's not something that can be done quickly, and it may not even be a good idea for project like hipSYCL to have this as *top* priority given limited development resources:

Official conformance only means that your implementation has been officially validated by Khronos. But since an implementation that has not gone through the official validation process might work just as well, it's not strictly necessary in my opinion. Especially for a university project such as hipSYCL, spending a lot of effort on that official validation (that usually also comes with a fee that we would have to pay) may not be so attractive compared to spending that time on optimizing performance and improving the experience for users with the most important features.

**Comment by illuhad** [comment] 2021-05-09 00:04
Support for `abs` (and many other builtins) has been added by now, so closing this.

**Closed as completed by illuhad** 2021-05-09 00:04 UTC
