### ISSUE TITLE
Unable to use accessor inside __hipsycl_if_target_hip

### ISSUE THREAD

**Issue by misos1** [AdaptiveCpp/AdaptiveCpp#870] opened 2022-11-20 19:36 UTC
**Bug summary**
Seems accessor used inside `__hipsycl_if_target_hip` is not registered.

```
[hipSYCL Warning] kernel_operation: Could not find embedded pointer in kernel blob for this requirement; do you have unnecessary accessors that are unused in your kernel?
:0:rocdevice.cpp            :2659: 12919517675 us: 484204: [tid:0x7fb7c5400700] Device::callbackQueue aborting with error : HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION: The agent attempted to access memory beyond the largest legal address. code: 0x29
```

**To Reproduce**
``` c++
	int a = 1;
	sycl::buffer<int> buf(&a, 1);
	sycl::queue().submit([&](sycl::handler &h)
	{
		auto ac = buf.get_access(h);
		h.single_task([=]()
		{
			__hipsycl_if_target_hip(
				printf("%i\n", ac[0]);
			);
		});
	});
```

Btw once I forgot to use `sycl::handler` as argument to `get_access` function so I called it without arguments like `buf.get_access()` and I had hard time to notice this subtle bug where I was getting similar error `HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION`. Is this what `get_access` should do without any argument and is usage of such accessor considered as UB?

**Comment by illuhad** [comment] 2022-11-20 21:00
> Seems accessor used inside __hipsycl_if_target_hip is not registered.

This is a C++ problem, not a hipSYCL problem ;) First of all, hipSYCL supports multiple compilation models (single pass compilation, and multipass compilation, where host and device have distinct compiler invocations).
`__hipsycl_if_target_*` is an abstraction that works across both single and multipass models.

HIP has a multipass compilation model. In a multipass compilation model, the device compilation has its own distinct compiler invocation, and `__hipsycl_if_target` is mapped to macro, so effectively you are expressing something like this:

```c++
	int a = 1;
	sycl::buffer<int> buf(&a, 1);
	sycl::queue().submit([&](sycl::handler &h)
	{
		auto ac = buf.get_access(h);
		h.single_task([=]()
		{
#ifdef IS_HIP_DEVICE_PASS
				printf("%i\n", ac[0]);
#endif
			);
		});
	});
```

In other words, in the host pass, you just have an empty kernel that does nothing. Because the lambda does nothing, the automatic capture expressed in `[=]` also captures nothing, because no accessors are actually used inside the kernel.

The device side however still sees the accessor as being used in the kernel, because for it `IS_HIP_DEVICE_PASS`  is defined.

Consequently, you have a mismatch in the data layout of the lambda between host and device.
The conclusion: Macros are evil, and if you do `__hipsycl_if_target_*` in a way that the accessor usage changes between host and device, better explicitly capture the accessor instead of relying on automatic capture to avoid such mismatches:
```c++
h.single_task([ac](){
   ...
});
```

> Btw once I forgot to use sycl::handler as argument to get_access function so I called it without arguments like buf.get_access() and I had hard time to notice this subtle bug where I was getting similar error HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION. Is this what get_access should do without any argument and is usage of such accessor considered as UB?

This is UB. It's one of the less fortunate APIs in SYCL that `get_access` without command group handler constructs a host accessor, not a device accessor.
Because host accessors block, using one in your command group handler might deadlock, or if it doesn't, it will lead to an invalid memory access inside the kernel because it holds a host pointer, not a device pointer.
Host accessors are intended to be used outside of command group functions, hence the constructor without command group handler object.

**Comment by illuhad** [comment] 2022-11-23 15:24
Closing because not a bug in hipSYCL

**Closed as completed by illuhad** 2022-11-23 15:24 UTC
Labels: bug
