### ISSUE TITLE
Apparent regression in get_info<sycl::info::event::command_execution_status>

### ISSUE THREAD

**Issue by facuMH** [AdaptiveCpp/AdaptiveCpp#599] opened 2021-07-26 14:47 UTC
**Bug summary**
when waiting for an event to complete, get_info<sycl::info::event::command_execution_status>() never returns complete.

**To Reproduce**
``` C++
int main() {
  sycl::queue queue(select_device(), make_async_handler());
  sycl::buffer<float, 1> buf(sycl::range<1>(1));

  auto e1 = queue.submit([&](sycl::handler &cgh) {
    auto ptr = buf.get_access<sycl::access::mode::read_write>(cgh);
    cgh.single_task<class FooBar>([=]() {
      ptr[0] = 1.f;
    });
  });


  while (e1.get_info<sycl::info::event::command_execution_status>() !=
         sycl::info::event_command_status::complete) {  }
  puts("Done");

  return 0;
}
``` 

**Expected behavior**
An event reports status complete

**Adititional Info**
After a little bisect the error seems to be introduced in commit 63c50f5afdfe695f9e4c1993b04d26ac5216e7ad
Also adding a wait e1.wait()  prevents the bug from reproducing.

**Comment by illuhad** [comment] 2021-07-26 15:18
IMO this code is not guaranteed to work by the SYCL spec because it is not defined when work is actually flushed to backends. hipSYCL might wait for more work in order to submit multiple kernels in a batch, so your kernel might never start execution until you actually wait on it.

My interpretation is that this query is merely there to query status, it does not guarantee progress. 

Do you have reason to believe that the kernel has actually started to *run*, and it never completes?

**Comment by psalz** [comment] 2021-07-27 07:36
> IMO this code is not guaranteed to work by the SYCL spec because it is not defined when work is actually flushed to backends. hipSYCL might wait for more work in order to submit multiple kernels in a batch, so your kernel might never start execution until you actually wait on it.

Hm, that's fair. However, as far as I can tell, `event::wait` (and even `queue::wait`, for that matter) doesn't give you any guarantees about work being flushed either (only that the calling thread will be blocked until the work has completed, but an implementation could still wait for other threads to submit more work). This seems wonky. Maybe there should be an explicit `queue::flush`..?

Anyway, since this breaks Celerity, how would you suggest working around this for the time being? `std::async([&]() { e1.wait(); });`?

**Comment by illuhad** [comment] 2021-07-27 10:09
> Hm, that's fair. However, as far as I can tell, event::wait (and even queue::wait, for that matter) doesn't give you any guarantees about work being flushed either (only that the calling thread will be blocked until the work has completed, but an implementation could still wait for other threads to submit more work)

In principle I think you are right. But any SYCL implementation that desires performance will attempt to minimize the user thread stalling and waiting, since this is what actually matters for the application runtime. So, if a SYCL implementation has not flushed by then, it better flush when the user is waiting on an event :) While it can be an interesting research topic to experiment with non-flushing `wait()`, I don't think this can ever show up in a production implementation because it might cause deadlocks if the user thread waits for something which does not progress on its own.

We could add some additional logic to flush every x milliseconds if no new work has come in, but it would not address the root problem and is not ideal either. After all, it would add some latency to this code pattern on average, which you would not want if you use this pattern for synchronization.

Can you maybe explain in some more detail why celerity uses this pattern?

In plain SYCL an asynchronous `event::wait()` as you propose is probably your best bet. What you really want would be hipSYCL's `application::dag().flush_async()`, if you don't mind implementation-specific workarounds.

> Maybe there should be an explicit queue::flush

maybe. I think the expectation of users would be that a `queue::flush()` has finished flushing after being called, which for your use case might be overkill - you don't want to wait until the flush is complete, you just want to ensure that progress is made in the background (which is what `dag().flush_async()` does in hipSYCL).

**Comment by psalz** [comment] 2021-07-27 14:50
> But any SYCL implementation that desires performance will attempt to minimize the user thread stalling and waiting, since this is what actually matters for the application runtime.

Couldn't that same argument then be applied to the above example as well? Consider a user submitting an expensive kernel, doing some host-side work within the submitting thread, and then waiting for the kernel result? With the current behavior, host and device side work is not being overlapped at all, resulting in increased application runtime.

> We could add some additional logic to flush every x milliseconds if no new work has come in, but it would not address the root problem and is not ideal either. After all, it would add some latency to this code pattern on average, which you would not want if you use this pattern for synchronization.

Agreed!

> Can you maybe explain in some more detail why celerity uses this pattern?

Celerity internally uses an "executor loop" that basically manages a bunch of asynchronous operations (such as device-side work, work in other threads or non-blocking MPI transfers) by submitting those operations once and then continuously polling for their execution status. One of the big advantages of that is, since all of this is happening in a single thread, we don't have to care about race conditions and locking in a lot of the internal logic. However for this to work we assume that asynchronous operations are cheap to submit and also that it's cheap to query their execution status ...and as it turns out we assume that there is some kind of progress guarantee :-).

> What you really want would be hipSYCL's application::dag().flush_async(), if you don't mind implementation-specific workarounds.

Sounds good. We already have a bunch of implementation-specific workarounds anyway, so one more won't hurt I guess ;-).

> I think the expectation of users would be that a queue::flush() has finished flushing after being called, which for your use case might be overkill - you don't want to wait until the flush is complete, you just want to ensure that progress is made in the background (which is what dag().flush_async() does in hipSYCL).

I'm not sure whether there is any use in knowing that the work has actually been flushed after the call returns, but yes, maybe it should be called `queue::flush_async` instead!

**Comment by illuhad** [comment] 2021-07-27 15:34
> Couldn't that same argument then be applied to the above example as well? Consider a user submitting an expensive kernel, doing some host-side work within the submitting thread, and then waiting for the kernel result? With the current behavior, host and device side work is not being overlapped at all, resulting in increased application runtime.

I think there are two points that distinguish this case:
* The SYCL implementation cannot actually know that you are using this query to wait and rely on progress. You could also just be using this query to check status.
* The idiomatic SYCL solution if you want host/device overlap is probably to use SYCL host tasks in addition to your kernels, and run everything through the SYCL DAG.

> Celerity internally uses an "executor loop" that basically manages a bunch of asynchronous operations (such as device-side work, work in other threads or non-blocking MPI transfers) by submitting those operations once and then continuously polling for their execution status. 

It's not clear to me yet why you cannot use the regular event synchronization API?

> I'm not sure whether there is any use in knowing that the work has actually been flushed after the call returns, but yes, maybe it should be called queue::flush_async instead!

I think there are some use cases for synchronous flushes. For example, if you want to isolate runtime overheads for some benchmarking purposes, since a synchronous flush would also include scheduling/submission time.

Another alternative I see might be to add something like an `eager` queue property that tells the implementation to flush right away. This would fix you issue in a more idiomatic way than a `queue::flush_async()`, but might be very detrimental for the performance of some backends, especially when we add task-graph-based backends such as TBB in the future. In this case, we would absolutely want to queue up multiple kernels to build up some backend task graph in the background.

**Comment by psalz** [comment] 2021-07-27 16:03
> The SYCL implementation cannot actually know that you are using this query to wait and rely on progress. You could also just be using this query to check status.

Yes sorry, I meant using `event::wait`, not the query loop. With the current behavior of the runtime, a single kernel would not be overlapped with host-side work (outside of a `host_task` -- which people will attempt, whether it's idiomatic or not).

> It's not clear to me yet why you cannot use the regular event synchronization API?

Because blocking the executor loop (which is a single thread) prevents new work from being submitted, MPI transfers from being updated etc. So we can't do that.

> Another alternative I see might be to add something like an eager queue property that tells the implementation to flush right away.

That could work as well, yes. An implementation could also issue a warning if it thinks an eager queue is not ideal for the given backend.

**Comment by illuhad** [comment] 2021-07-27 21:46
> Yes sorry, I meant using event::wait, not the query loop. With the current behavior of the runtime, a single kernel would not be overlapped with host-side work (outside of a host_task -- which people will attempt, whether it's idiomatic or not).

Well this really is an implementation detail of the current flush heuristic, not a fundamental issue of the runtime design. Every individual submission (i.e. call to `queue::submit()`) triggers a flush opportunity (not only calls to `wait()` or other synchronization), and while the flush heuristic at the moment is extremely simplistic it is not planned for it to stay that way in the long run. https://github.com/illuhad/hipSYCL/blob/c759aac1d9e07cceb7c0ee14c2dc2c9f83074c71/src/runtime/dag_manager.cpp#L162

In the end it's a tradeoff between efficiently scheduling SYCL operations and having overlap with host execution.

You can recover the old behavior by setting the environment variable `HIPSYCL_RT_SCHEDULER=direct`, although the plan is to make `max_cached_dag_nodes` itself configurable which would be a better solution than using a less powerful scheduler.

> Because blocking the executor loop (which is a single thread) prevents new work from being submitted, MPI transfers from being updated etc. So we can't do that.

Ah I see. To me this sounds like we should maybe look into asynchronous waiting mechanisms in the SYCL WG for such use cases.

**Comment by pszi1ard** [comment] 2021-08-27 10:23
In GROMACS we generally want eager submission and no caching at all (at least not on most of the critical path), both because we rely on CPU--GPU overlap and as application is very latency sensitive and often overlapping the CPU launch with useful GPU work can have a performance impact. An an `eager` queue property would work for us quite well, that may even allow experimenting with combining eager and lazy scheduling (although we'd probably want `max_cached_dag_nodes` configurable too).

**Comment by illuhad** [comment] 2022-05-20 23:11
Closing because not really a regression in hipSYCL; low-latency/eager queues is a more general open question.

**Closed as completed by illuhad** 2022-05-20 23:11 UTC
Labels: bug
